version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "app.surveyname.com"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm config set "@fortawesome:registry" https://npm.fontawesome.com/ 
            - npm config set "//npm.fontawesome.com/:_authToken" EE97B62E-226E-42C3-BCBC-4D2FD10216A7
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build
    post_build:
         commands:
            - aws s3 rm s3://${S3_BUCKET} --recursive
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes